In [1]:
import torch
import numpy
from torch.autograd import Variable
from torch import nn, optim

In [2]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
float_tensor = torch.randn([3, 4, 5], dtype=torch.float32)

In [5]:
print_tens_info(float_tensor)

X :
tensor([[[ 1.0616, -0.7342, -0.1813, -0.8149,  0.1908],
         [-0.8918,  0.0335, -0.2314, -1.1038,  0.9501],
         [-0.1919,  0.9367, -0.2431, -0.5796, -0.1525],
         [ 0.3327, -1.4845, -0.5393, -0.6685, -1.0334]],

        [[-0.0606,  0.5138, -0.3707,  0.3148, -0.7273],
         [ 0.2801, -0.1472,  0.5114,  1.3711, -1.0277],
         [-0.5207, -0.0032, -0.0509,  1.4697, -0.3172],
         [ 0.4646, -0.7165, -1.2748, -1.0761, -0.2809]],

        [[ 0.7573,  1.2063,  0.8737,  2.9353, -0.2775],
         [ 1.5269, -0.8775, -0.7122,  1.1541,  1.3620],
         [-0.3093,  0.9470,  1.1246,  0.9050, -0.6075],
         [-0.6063, -2.0386,  0.4704,  0.5640, -0.0363]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [6]:
# Выведите его форму (shape)

In [7]:
float_tensor.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6 X 10

In [9]:
print_tens_info(float_tensor.view(6,10))
float_tensor_reshape = float_tensor.view(6,10)
float_tensor_reshape

X :
tensor([[ 1.0616, -0.7342, -0.1813, -0.8149,  0.1908, -0.8918,  0.0335, -0.2314,
         -1.1038,  0.9501],
        [-0.1919,  0.9367, -0.2431, -0.5796, -0.1525,  0.3327, -1.4845, -0.5393,
         -0.6685, -1.0334],
        [-0.0606,  0.5138, -0.3707,  0.3148, -0.7273,  0.2801, -0.1472,  0.5114,
          1.3711, -1.0277],
        [-0.5207, -0.0032, -0.0509,  1.4697, -0.3172,  0.4646, -0.7165, -1.2748,
         -1.0761, -0.2809],
        [ 0.7573,  1.2063,  0.8737,  2.9353, -0.2775,  1.5269, -0.8775, -0.7122,
          1.1541,  1.3620],
        [-0.3093,  0.9470,  1.1246,  0.9050, -0.6075, -0.6063, -2.0386,  0.4704,
          0.5640, -0.0363]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



tensor([[ 1.0616, -0.7342, -0.1813, -0.8149,  0.1908, -0.8918,  0.0335, -0.2314,
         -1.1038,  0.9501],
        [-0.1919,  0.9367, -0.2431, -0.5796, -0.1525,  0.3327, -1.4845, -0.5393,
         -0.6685, -1.0334],
        [-0.0606,  0.5138, -0.3707,  0.3148, -0.7273,  0.2801, -0.1472,  0.5114,
          1.3711, -1.0277],
        [-0.5207, -0.0032, -0.0509,  1.4697, -0.3172,  0.4646, -0.7165, -1.2748,
         -1.0761, -0.2809],
        [ 0.7573,  1.2063,  0.8737,  2.9353, -0.2775,  1.5269, -0.8775, -0.7122,
          1.1541,  1.3620],
        [-0.3093,  0.9470,  1.1246,  0.9050, -0.6075, -0.6063, -2.0386,  0.4704,
          0.5640, -0.0363]])

In [10]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [11]:
_vec =  [1, 4, 2, 2, 1]
tensor2 = torch.FloatTensor(_vec)
float_tensor*tensor2

tensor([[[ 1.0616, -2.9367, -0.3627, -1.6299,  0.1908],
         [-0.8918,  0.1339, -0.4627, -2.2076,  0.9501],
         [-0.1919,  3.7469, -0.4862, -1.1592, -0.1525],
         [ 0.3327, -5.9379, -1.0786, -1.3371, -1.0334]],

        [[-0.0606,  2.0553, -0.7414,  0.6297, -0.7273],
         [ 0.2801, -0.5889,  1.0228,  2.7423, -1.0277],
         [-0.5207, -0.0130, -0.1019,  2.9395, -0.3172],
         [ 0.4646, -2.8658, -2.5496, -2.1523, -0.2809]],

        [[ 0.7573,  4.8252,  1.7474,  5.8705, -0.2775],
         [ 1.5269, -3.5098, -1.4245,  2.3082,  1.3620],
         [-0.3093,  3.7880,  2.2492,  1.8100, -0.6075],
         [-0.6063, -8.1543,  0.9408,  1.1279, -0.0363]]])

In [12]:
_vec1 =  [1, 4, 2, 2, 1, 1, 4, 2, 2, 1,]
tensor3 = torch.FloatTensor(_vec1)
float_tensor_reshape* tensor3

tensor([[ 1.0616, -2.9367, -0.3627, -1.6299,  0.1908, -0.8918,  0.1339, -0.4627,
         -2.2076,  0.9501],
        [-0.1919,  3.7469, -0.4862, -1.1592, -0.1525,  0.3327, -5.9379, -1.0786,
         -1.3371, -1.0334],
        [-0.0606,  2.0553, -0.7414,  0.6297, -0.7273,  0.2801, -0.5889,  1.0228,
          2.7423, -1.0277],
        [-0.5207, -0.0130, -0.1019,  2.9395, -0.3172,  0.4646, -2.8658, -2.5496,
         -2.1523, -0.2809],
        [ 0.7573,  4.8252,  1.7474,  5.8705, -0.2775,  1.5269, -3.5098, -1.4245,
          2.3082,  1.3620],
        [-0.3093,  3.7880,  2.2492,  1.8100, -0.6075, -0.6063, -8.1543,  0.9408,
          1.1279, -0.0363]])

In [13]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [14]:
print_tens_info(torch.matmul(float_tensor_reshape, float_tensor_reshape.T))
torch.matmul(float_tensor_reshape, float_tensor_reshape.T)

X :
tensor([[ 5.3705, -0.8696, -3.6326, -1.0218, -3.8913, -2.3743],
        [-0.8696,  5.4525,  0.6927,  2.2211, -0.8711,  2.4725],
        [-3.6326,  0.6927,  4.3310, -0.8610,  1.7513,  1.9966],
        [-1.0218,  2.2211, -0.8610,  6.1257,  4.5809,  1.6060],
        [-3.8913, -0.8711,  1.7513,  4.5809, 18.2801,  5.8449],
        [-2.3743,  2.4725,  1.9966,  1.6060,  5.8449,  8.5094]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



tensor([[ 5.3705, -0.8696, -3.6326, -1.0218, -3.8913, -2.3743],
        [-0.8696,  5.4525,  0.6927,  2.2211, -0.8711,  2.4725],
        [-3.6326,  0.6927,  4.3310, -0.8610,  1.7513,  1.9966],
        [-1.0218,  2.2211, -0.8610,  6.1257,  4.5809,  1.6060],
        [-3.8913, -0.8711,  1.7513,  4.5809, 18.2801,  5.8449],
        [-2.3743,  2.4725,  1.9966,  1.6060,  5.8449,  8.5094]])

In [15]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [16]:
def get_derivative_func(coordinates:list = [1, 0.5, 2]):
    """производные функции y = x**3 + z - 75t в точке (1, 0.5, 2)
    вывод: [производная по x, z, t]"""
    
    x = Variable(torch.ones(1)*coordinates[0], requires_grad = True)
    z = Variable(torch.ones(1)*coordinates[1], requires_grad = True)
    t = Variable(torch.ones(1)*coordinates[2], requires_grad = True)

    y = x**3 + z - 75*t
    y.backward(torch.ones(1))
    
    print(f'x.grad: {x.grad}\nz.grad: {z.grad}\nt.grad: {t.grad}\n')

In [17]:
print(3*1**2)
get_derivative_func()

3
x.grad: tensor([3.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [18]:
print(3*2**2)
get_derivative_func(coordinates=[2, 67, 98])

12
x.grad: tensor([12.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [19]:
print(3*6**2)
get_derivative_func(coordinates=[6, 67, 98])

108
x.grad: tensor([108.])
z.grad: tensor([1.])
t.grad: tensor([-75.])



In [20]:
# Создайте единичный тензор размера 5x6

In [21]:
ones_tensor = torch.ones(5,6)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [22]:
# Переведите его в формат numpy

In [23]:
ones_tensor.numpy()


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [24]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 

In [62]:
def get_optimization_func(coordinat_x=1):
    """y = x**w - 2*x**2 + 5 in coordinat_x"""
    x = torch.ones(1)*coordinat_x
    w = Variable(torch.ones(1), requires_grad = True)

    optimizer = optim.SGD([w], lr=0.01)
    criterion = nn.MSELoss()
    optimizer.zero_grad()

    y = x**w - 2*x**2 + 5
    loss = criterion(y, torch.ones(1)*10)
    print(f"loss:\n\t{loss.item()}")
    loss.backward()
    optimizer.step()
    print(f"y = x**w - 2*x**2 + 5:\n\t{y}")
    print(f"w.grad:\n\t{w.grad}")

In [63]:
for coordiant in range(10):
    get_optimization_func(coordinat_x=coordiant)
    print('=='*33)

loss:
	25.0
y = x**w - 2*x**2 + 5:
	tensor([5.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-0.])
loss:
	36.0
y = x**w - 2*x**2 + 5:
	tensor([4.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-0.])
loss:
	121.0
y = x**w - 2*x**2 + 5:
	tensor([-1.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-30.4985])
loss:
	400.0
y = x**w - 2*x**2 + 5:
	tensor([-10.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-131.8335])
loss:
	1089.0
y = x**w - 2*x**2 + 5:
	tensor([-23.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-365.9817])
loss:
	2500.0
y = x**w - 2*x**2 + 5:
	tensor([-40.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-804.7190])
loss:
	5041.0
y = x**w - 2*x**2 + 5:
	tensor([-61.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-1526.5791])
loss:
	9216.0
y = x**w - 2*x**2 + 5:
	tensor([-86.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-2615.3032])
loss:
	15625.0
y = x**w - 2*x**2 + 5:
	tensor([-115.], grad_fn=<AddBackward0>)
w.grad:
	tensor([-4158.8833])
loss:
	24964.0
y = x**w - 2*x**2 + 5:
	tensor([-148.], grad_fn=<A