In [1]:
import torch
import numpy

In [2]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))

In [3]:
# Создайте случайный FloatTensor размера 3x4x5

In [4]:
float_tensor = torch.randn([3, 4, 5], dtype=torch.float32)

In [5]:
print_tens_info(float_tensor)

X :
tensor([[[ 1.1213, -1.9208, -0.7840,  0.7654, -0.6889],
         [ 2.3118,  0.2982,  1.5958, -0.9215,  1.2654],
         [-0.3747,  1.5289, -0.2027,  0.0955,  0.0629],
         [-0.8784,  0.8725,  0.1265,  1.6435, -0.5921]],

        [[ 1.7344, -2.2482,  1.4238, -0.5325,  0.3568],
         [ 0.0802,  1.1735,  0.3156,  1.2453,  0.9700],
         [ 0.6401, -1.0724,  1.1040,  0.3424, -0.6004],
         [-0.0505, -0.8985,  0.1412,  0.1595, -0.0342]],

        [[-0.2772,  1.9403,  0.0135, -0.0151, -0.7687],
         [-1.5204,  0.3419, -1.2904,  0.5402,  0.8428],
         [ 0.9683, -0.2611,  0.8356, -0.2188, -2.5456],
         [ 1.3059,  0.3054,  0.0193, -1.8541, -1.0466]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [6]:
# Выведите его форму (shape)

In [7]:
float_tensor.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6 X 10

In [9]:
print_tens_info(float_tensor.view(6,10))
float_tensor_reshape = float_tensor.view(6,10)


X :
tensor([[ 1.1213, -1.9208, -0.7840,  0.7654, -0.6889,  2.3118,  0.2982,  1.5958,
         -0.9215,  1.2654],
        [-0.3747,  1.5289, -0.2027,  0.0955,  0.0629, -0.8784,  0.8725,  0.1265,
          1.6435, -0.5921],
        [ 1.7344, -2.2482,  1.4238, -0.5325,  0.3568,  0.0802,  1.1735,  0.3156,
          1.2453,  0.9700],
        [ 0.6401, -1.0724,  1.1040,  0.3424, -0.6004, -0.0505, -0.8985,  0.1412,
          0.1595, -0.0342],
        [-0.2772,  1.9403,  0.0135, -0.0151, -0.7687, -1.5204,  0.3419, -1.2904,
          0.5402,  0.8428],
        [ 0.9683, -0.2611,  0.8356, -0.2188, -2.5456,  1.3059,  0.3054,  0.0193,
         -1.8541, -1.0466]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [10]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [11]:
_vec =  [1, 4, 2, 2, 1]
tensor2 = torch.FloatTensor(_vec)
torch.matmul(float_tensor, tensor2)

tensor([[-7.2882,  6.1187,  5.5895,  5.5594],
        [-5.1193,  8.8660, -1.3570, -3.0776],
        [ 6.7120, -0.8104, -1.3882, -2.1884]])

In [12]:
_vec1 =  [1, 4, 2, 2, 1, 1, 4, 2, 2, 1,]
tensor3 = torch.FloatTensor(_vec1)
torch.matmul(float_tensor_reshape, tensor3)

tensor([-1.1695, 11.1490,  3.7467, -4.4347,  5.9016, -3.5767])

In [13]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [14]:
print_tens_info(torch.matmul(float_tensor_reshape, float_tensor_reshape.T))
torch.matmul(float_tensor_reshape, float_tensor_reshape.T)

X :
tensor([[17.0526, -7.0008,  5.6126,  2.2381, -8.4339,  6.0435],
        [-7.0008,  7.1328, -1.9385, -2.5476,  4.8773, -4.4181],
        [ 5.6126, -1.9385, 14.4755,  3.8479, -3.7278, -0.1903],
        [ 2.2381, -2.5476,  3.8479,  4.1128, -2.1422,  2.6783],
        [-8.4339,  4.8773, -3.7278, -2.1422,  9.5285, -2.5935],
        [ 6.0435, -4.4181, -0.1903,  2.6783, -2.5935, 14.5638]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



tensor([[17.0526, -7.0008,  5.6126,  2.2381, -8.4339,  6.0435],
        [-7.0008,  7.1328, -1.9385, -2.5476,  4.8773, -4.4181],
        [ 5.6126, -1.9385, 14.4755,  3.8479, -3.7278, -0.1903],
        [ 2.2381, -2.5476,  3.8479,  4.1128, -2.1422,  2.6783],
        [-8.4339,  4.8773, -3.7278, -2.1422,  9.5285, -2.5935],
        [ 6.0435, -4.4181, -0.1903,  2.6783, -2.5935, 14.5638]])

In [15]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [16]:
torch.ones(3)*2

tensor([2., 2., 2.])

In [17]:
from torch.autograd import Variable
x0 = Variable(torch.ones(3), requires_grad = True)
z0 = Variable(torch.ones(3), requires_grad = True)
t0 = Variable(torch.ones(3), requires_grad = True)

x1 = Variable(torch.ones(3)*0.5, requires_grad = True)
z1 = Variable(torch.ones(3)*0.5, requires_grad = True)
t1 = Variable(torch.ones(3)*0.5, requires_grad = True)

x2 = Variable(torch.ones(3)*2, requires_grad = True)
z2 = Variable(torch.ones(3)*2, requires_grad = True)
t2 = Variable(torch.ones(3)*2, requires_grad = True)


x = Variable(torch.ones(3), requires_grad = True)
z = Variable(torch.ones(3)*0.5, requires_grad = True)
t = Variable(torch.ones(3)*2, requires_grad = True)

In [18]:
y0 = x0**3 + z0 - 75*t0
y1 = x1**3 + z1 - 75*t1
y2 = x2**3 + z2 - 75*t2


y = x**3 + z - 75*t

In [19]:
print_tens_info(y0)
print_tens_info(y1)
print_tens_info(y2)

print_tens_info(y)

X :
tensor([-73., -73., -73.], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor

X :
tensor([-36.8750, -36.8750, -36.8750], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor

X :
tensor([-140., -140., -140.], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor

X :
tensor([-148.5000, -148.5000, -148.5000], grad_fn=<SubBackward0>)

X количество измерений:
1

X размеры :  torch.Size([3])
X тип : torch.FloatTensor



In [20]:
y0.backward(torch.ones(3))
print(x0.grad)
print(z0.grad)
print(t0.grad)

tensor([3., 3., 3.])
tensor([1., 1., 1.])
tensor([-75., -75., -75.])


In [21]:
y1.backward(torch.ones(3)*.5)
print(x1.grad)
print(z1.grad)
print(t1.grad)

tensor([0.3750, 0.3750, 0.3750])
tensor([0.5000, 0.5000, 0.5000])
tensor([-37.5000, -37.5000, -37.5000])


In [22]:
y2.backward(torch.ones(3)*2)
print(x2.grad)
print(z2.grad)
print(t2.grad)

tensor([24., 24., 24.])
tensor([2., 2., 2.])
tensor([-150., -150., -150.])


In [23]:
y.backward(torch.ones(3))
print(x.grad)
print(z.grad)
print(t.grad)

tensor([3., 3., 3.])
tensor([1., 1., 1.])
tensor([-75., -75., -75.])


In [24]:
# Создайте единичный тензор размера 5x6

In [25]:
ones_tensor = torch.ones(5,6)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [26]:
# Переведите его в формат numpy

In [27]:
ones_tensor.numpy()


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [28]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 